# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Cheongwoong Kang
name: Cheongwoong Kang
email: cw.kang@kaist.ac.kr
occupation: Ph.D. Candidate
employer: KAIST
url: https://cheongwoong.github.io # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/
icon: favicon.ico # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

# Dimensions
max_width: 800px